/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CanvaRouteImport } from './routes/canva'
import { Route as ClaseRouteImport } from './routes/clase'
import { Route as GuiaRouteImport } from './routes/guia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvaRoute = CanvaRouteImport.update({
  id: '/canva',
  path: '/canva',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaseRoute = ClaseRouteImport.update({
  id: '/clase',
  path: '/clase',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/canva': typeof CanvaRoute
  '/clase': typeof ClaseRoute
  '/guia': typeof GuiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/canva': typeof CanvaRoute
  '/clase': typeof ClaseRoute
  '/guia': typeof GuiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/canva': typeof CanvaRoute
  '/clase': typeof ClaseRoute
  '/guia': typeof GuiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atlas' | '/canva' | '/clase' | '/guia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atlas' | '/canva' | '/clase' | '/guia'
  id: '__root__' | '/' | '/atlas' | '/canva' | '/clase' | '/guia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  CanvaRoute: typeof CanvaRoute
  ClaseRoute: typeof ClaseRoute
  GuiaRoute: typeof GuiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canva': {
      id: '/canva'
      path: '/canva'
      fullPath: '/canva'
      preLoaderRoute: typeof CanvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clase': {
      id: '/clase'
      path: '/clase'
      fullPath: '/clase'
      preLoaderRoute: typeof ClaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  CanvaRoute: CanvaRoute,
  ClaseRoute: ClaseRoute,
  GuiaRoute: GuiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
